const EVENT_CREATED = 'create';
const EVENT_REMOVE = 'remove';
const EVENT_EDITED = 'edit';
const EVENT_ACCESS = 'access';
const EVENT_UNHANDLED = 'lost';

module.exports = {
    EVENT_CREATED: EVENT_CREATED,
    EVENT_REMOVE: EVENT_REMOVE,
    EVENT_EDITED: EVENT_EDITED,
    EVENT_ACCESS: EVENT_ACCESS,
    EVENT_UNHANDLED: EVENT_UNHANDLED
}